// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "f13ae899443405d0356fa8327559ce2415d6eca5d6b475bd79bb4a19a5c03f03"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            Password = "9fad83113b7f41052f614e3ad6d99e025a404635268e372fd73ab195aa57ef4b"
                        },
                        new
                        {
                            Id = 3,
                            Email = "michael.johnson@example.com",
                            FirstName = "Michael",
                            LastName = "Johnson",
                            Password = "0d03517e6dfa1b5d4bfb0f627e25b3f6699ff31a0a5c31a3fb098fd5495b4779"
                        },
                        new
                        {
                            Id = 4,
                            Email = "emily.davis@example.com",
                            FirstName = "Emily",
                            LastName = "Davis",
                            Password = "363b9c3766022ad67ff6a75491fdd501cc2e8e39b994c4f36363f0d26e82a12c"
                        },
                        new
                        {
                            Id = 5,
                            Email = "chris.brown@example.com",
                            FirstName = "Chris",
                            LastName = "Brown",
                            Password = "a9517c1b6c910ebc2d7c6c59ff08e14e14e511301ac7683b3538405b047ed6d3"
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Email = "mr.admin.number1@gmail.com",
                            FirstName = "Admin",
                            LastName = "Your best",
                            Password = "daee8940d0fbf19005e13de32ce11a5f56dbdf6516c6c527e66a67a815cecce6"
                        },
                        new
                        {
                            Id = 7,
                            Email = "mr.admin.number2@gmail.com",
                            FirstName = "Admin",
                            LastName = "Your second best",
                            Password = "9fad83113b7f41052f614e3ad6d99e025a404635268e372fd73ab195aa57ef4b"
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.FinanceOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("FinanceOperations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 500L,
                            Date = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100L,
                            Date = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 750L,
                            Date = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 120L,
                            Date = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1500L,
                            Date = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 5
                        },
                        new
                        {
                            Id = 6,
                            Amount = 60L,
                            Date = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 6
                        },
                        new
                        {
                            Id = 7,
                            Amount = 40L,
                            Date = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 7
                        },
                        new
                        {
                            Id = 8,
                            Amount = 100L,
                            Date = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 8
                        },
                        new
                        {
                            Id = 9,
                            Amount = 2000L,
                            Date = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 9
                        },
                        new
                        {
                            Id = 10,
                            Amount = 300L,
                            Date = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 10
                        },
                        new
                        {
                            Id = 11,
                            Amount = 150L,
                            Date = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 11
                        },
                        new
                        {
                            Id = 12,
                            Amount = 200L,
                            Date = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 12
                        },
                        new
                        {
                            Id = 13,
                            Amount = 300L,
                            Date = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 13
                        },
                        new
                        {
                            Id = 14,
                            Amount = 70L,
                            Date = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 14
                        },
                        new
                        {
                            Id = 15,
                            Amount = 50L,
                            Date = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 15
                        },
                        new
                        {
                            Id = 16,
                            Amount = 1000L,
                            Date = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 16
                        },
                        new
                        {
                            Id = 17,
                            Amount = 200L,
                            Date = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 17
                        },
                        new
                        {
                            Id = 18,
                            Amount = 250L,
                            Date = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 18
                        },
                        new
                        {
                            Id = 19,
                            Amount = 80L,
                            Date = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 19
                        },
                        new
                        {
                            Id = 20,
                            Amount = 50L,
                            Date = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 20
                        },
                        new
                        {
                            Id = 21,
                            Amount = 300L,
                            Date = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 21
                        },
                        new
                        {
                            Id = 22,
                            Amount = 500L,
                            Date = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 22
                        },
                        new
                        {
                            Id = 23,
                            Amount = 1500L,
                            Date = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 23
                        },
                        new
                        {
                            Id = 24,
                            Amount = 40L,
                            Date = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 24
                        },
                        new
                        {
                            Id = 25,
                            Amount = 600L,
                            Date = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 25
                        },
                        new
                        {
                            Id = 26,
                            Amount = 100L,
                            Date = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 26
                        },
                        new
                        {
                            Id = 27,
                            Amount = 400L,
                            Date = new DateTime(2024, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 27
                        },
                        new
                        {
                            Id = 28,
                            Amount = 300L,
                            Date = new DateTime(2024, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 28
                        },
                        new
                        {
                            Id = 29,
                            Amount = 500L,
                            Date = new DateTime(2024, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 29
                        },
                        new
                        {
                            Id = 30,
                            Amount = 20L,
                            Date = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 30
                        },
                        new
                        {
                            Id = 31,
                            Amount = 500L,
                            Date = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 1
                        },
                        new
                        {
                            Id = 32,
                            Amount = 100L,
                            Date = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 2
                        },
                        new
                        {
                            Id = 33,
                            Amount = 750L,
                            Date = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 3
                        },
                        new
                        {
                            Id = 34,
                            Amount = 120L,
                            Date = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 4
                        },
                        new
                        {
                            Id = 35,
                            Amount = 1500L,
                            Date = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 5
                        },
                        new
                        {
                            Id = 36,
                            Amount = 60L,
                            Date = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 6
                        },
                        new
                        {
                            Id = 37,
                            Amount = 40L,
                            Date = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 7
                        },
                        new
                        {
                            Id = 38,
                            Amount = 100L,
                            Date = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 8
                        },
                        new
                        {
                            Id = 39,
                            Amount = 2000L,
                            Date = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 9
                        },
                        new
                        {
                            Id = 40,
                            Amount = 300L,
                            Date = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 10
                        },
                        new
                        {
                            Id = 41,
                            Amount = 150L,
                            Date = new DateTime(2024, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 11
                        },
                        new
                        {
                            Id = 42,
                            Amount = 200L,
                            Date = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 12
                        },
                        new
                        {
                            Id = 43,
                            Amount = 300L,
                            Date = new DateTime(2024, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 13
                        },
                        new
                        {
                            Id = 44,
                            Amount = 70L,
                            Date = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 14
                        },
                        new
                        {
                            Id = 45,
                            Amount = 50L,
                            Date = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 15
                        },
                        new
                        {
                            Id = 46,
                            Amount = 1000L,
                            Date = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 16
                        },
                        new
                        {
                            Id = 47,
                            Amount = 200L,
                            Date = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 17
                        },
                        new
                        {
                            Id = 48,
                            Amount = 250L,
                            Date = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 18
                        },
                        new
                        {
                            Id = 49,
                            Amount = 80L,
                            Date = new DateTime(2024, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 19
                        },
                        new
                        {
                            Id = 50,
                            Amount = 50L,
                            Date = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 20
                        },
                        new
                        {
                            Id = 51,
                            Amount = 300L,
                            Date = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 21
                        },
                        new
                        {
                            Id = 52,
                            Amount = 500L,
                            Date = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 22
                        },
                        new
                        {
                            Id = 53,
                            Amount = 1500L,
                            Date = new DateTime(2024, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 23
                        },
                        new
                        {
                            Id = 54,
                            Amount = 40L,
                            Date = new DateTime(2024, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 24
                        },
                        new
                        {
                            Id = 55,
                            Amount = 600L,
                            Date = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 25
                        },
                        new
                        {
                            Id = 56,
                            Amount = 100L,
                            Date = new DateTime(2024, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 26
                        },
                        new
                        {
                            Id = 57,
                            Amount = 400L,
                            Date = new DateTime(2024, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 27
                        },
                        new
                        {
                            Id = 58,
                            Amount = 300L,
                            Date = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 28
                        },
                        new
                        {
                            Id = 59,
                            Amount = 500L,
                            Date = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 29
                        },
                        new
                        {
                            Id = 60,
                            Amount = 20L,
                            Date = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 30
                        },
                        new
                        {
                            Id = 61,
                            Amount = 500L,
                            Date = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 1
                        },
                        new
                        {
                            Id = 62,
                            Amount = 100L,
                            Date = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 2
                        },
                        new
                        {
                            Id = 63,
                            Amount = 750L,
                            Date = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 3
                        },
                        new
                        {
                            Id = 64,
                            Amount = 120L,
                            Date = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 4
                        },
                        new
                        {
                            Id = 65,
                            Amount = 1500L,
                            Date = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 5
                        },
                        new
                        {
                            Id = 66,
                            Amount = 60L,
                            Date = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 6
                        },
                        new
                        {
                            Id = 67,
                            Amount = 40L,
                            Date = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 7
                        },
                        new
                        {
                            Id = 68,
                            Amount = 100L,
                            Date = new DateTime(2024, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 8
                        },
                        new
                        {
                            Id = 69,
                            Amount = 2000L,
                            Date = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 9
                        },
                        new
                        {
                            Id = 70,
                            Amount = 300L,
                            Date = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 10
                        },
                        new
                        {
                            Id = 71,
                            Amount = 150L,
                            Date = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 11
                        },
                        new
                        {
                            Id = 72,
                            Amount = 200L,
                            Date = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 12
                        },
                        new
                        {
                            Id = 73,
                            Amount = 300L,
                            Date = new DateTime(2024, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 13
                        },
                        new
                        {
                            Id = 74,
                            Amount = 70L,
                            Date = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 14
                        },
                        new
                        {
                            Id = 75,
                            Amount = 50L,
                            Date = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 15
                        },
                        new
                        {
                            Id = 76,
                            Amount = 1000L,
                            Date = new DateTime(2024, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 16
                        },
                        new
                        {
                            Id = 77,
                            Amount = 200L,
                            Date = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 17
                        },
                        new
                        {
                            Id = 78,
                            Amount = 250L,
                            Date = new DateTime(2024, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 18
                        },
                        new
                        {
                            Id = 79,
                            Amount = 80L,
                            Date = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 19
                        },
                        new
                        {
                            Id = 80,
                            Amount = 50L,
                            Date = new DateTime(2024, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 20
                        },
                        new
                        {
                            Id = 81,
                            Amount = 300L,
                            Date = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 21
                        },
                        new
                        {
                            Id = 82,
                            Amount = 500L,
                            Date = new DateTime(2024, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 22
                        },
                        new
                        {
                            Id = 83,
                            Amount = 1500L,
                            Date = new DateTime(2024, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 23
                        },
                        new
                        {
                            Id = 84,
                            Amount = 40L,
                            Date = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 24
                        },
                        new
                        {
                            Id = 85,
                            Amount = 600L,
                            Date = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 25
                        },
                        new
                        {
                            Id = 86,
                            Amount = 100L,
                            Date = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 26
                        },
                        new
                        {
                            Id = 87,
                            Amount = 400L,
                            Date = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 27
                        },
                        new
                        {
                            Id = 88,
                            Amount = 300L,
                            Date = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 28
                        },
                        new
                        {
                            Id = 89,
                            Amount = 500L,
                            Date = new DateTime(2024, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 29
                        },
                        new
                        {
                            Id = 90,
                            Amount = 20L,
                            Date = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 30
                        },
                        new
                        {
                            Id = 91,
                            Amount = 500L,
                            Date = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 1
                        },
                        new
                        {
                            Id = 92,
                            Amount = 100L,
                            Date = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 2
                        },
                        new
                        {
                            Id = 93,
                            Amount = 750L,
                            Date = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 3
                        },
                        new
                        {
                            Id = 94,
                            Amount = 120L,
                            Date = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 4
                        },
                        new
                        {
                            Id = 95,
                            Amount = 1500L,
                            Date = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 5
                        },
                        new
                        {
                            Id = 96,
                            Amount = 60L,
                            Date = new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 6
                        },
                        new
                        {
                            Id = 97,
                            Amount = 40L,
                            Date = new DateTime(2024, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 7
                        },
                        new
                        {
                            Id = 98,
                            Amount = 100L,
                            Date = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 8
                        },
                        new
                        {
                            Id = 99,
                            Amount = 2000L,
                            Date = new DateTime(2024, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 9
                        },
                        new
                        {
                            Id = 100,
                            Amount = 300L,
                            Date = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeId = 10
                        },
                        new
                        {
                            Id = 101,
                            Amount = 100L,
                            Date = new DateTime(2024, 4, 11, 3, 11, 24, 0, DateTimeKind.Unspecified),
                            TypeId = 1
                        },
                        new
                        {
                            Id = 102,
                            Amount = 2000L,
                            Date = new DateTime(2024, 4, 11, 11, 2, 53, 0, DateTimeKind.Unspecified),
                            TypeId = 1
                        },
                        new
                        {
                            Id = 103,
                            Amount = 300L,
                            Date = new DateTime(2024, 4, 11, 7, 27, 37, 0, DateTimeKind.Unspecified),
                            TypeId = 1
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.FinanceOperationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntryType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("FinanceOperationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Monthly salary",
                            EntryType = 0,
                            Name = "Salary",
                            WalletId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Weekly groceries",
                            EntryType = 1,
                            Name = "Groceries",
                            WalletId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Monthly rent payment",
                            EntryType = 1,
                            Name = "Rent",
                            WalletId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Monthly electricity bill",
                            EntryType = 1,
                            Name = "Electricity Bill",
                            WalletId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Freelance project payment",
                            EntryType = 0,
                            Name = "Freelance",
                            WalletId = 3
                        },
                        new
                        {
                            Id = 6,
                            Description = "Dinner at restaurant",
                            EntryType = 1,
                            Name = "Dining Out",
                            WalletId = 3
                        },
                        new
                        {
                            Id = 7,
                            Description = "Monthly gym membership",
                            EntryType = 1,
                            Name = "Gym Membership",
                            WalletId = 4
                        },
                        new
                        {
                            Id = 8,
                            Description = "Birthday gift",
                            EntryType = 1,
                            Name = "Gift",
                            WalletId = 4
                        },
                        new
                        {
                            Id = 9,
                            Description = "Consulting services",
                            EntryType = 0,
                            Name = "Consulting",
                            WalletId = 5
                        },
                        new
                        {
                            Id = 10,
                            Description = "Travel expenses",
                            EntryType = 1,
                            Name = "Travel",
                            WalletId = 5
                        },
                        new
                        {
                            Id = 11,
                            Description = "Stock market investment",
                            EntryType = 1,
                            Name = "Investment",
                            WalletId = 6
                        },
                        new
                        {
                            Id = 12,
                            Description = "Stock dividends",
                            EntryType = 0,
                            Name = "Dividends",
                            WalletId = 6
                        },
                        new
                        {
                            Id = 13,
                            Description = "Monthly savings",
                            EntryType = 0,
                            Name = "Savings",
                            WalletId = 7
                        },
                        new
                        {
                            Id = 14,
                            Description = "Car repair and maintenance",
                            EntryType = 1,
                            Name = "Car Maintenance",
                            WalletId = 7
                        },
                        new
                        {
                            Id = 15,
                            Description = "Monthly internet bill",
                            EntryType = 1,
                            Name = "Internet Bill",
                            WalletId = 1
                        },
                        new
                        {
                            Id = 16,
                            Description = "Annual bonus",
                            EntryType = 0,
                            Name = "Bonus",
                            WalletId = 1
                        },
                        new
                        {
                            Id = 17,
                            Description = "Health insurance payment",
                            EntryType = 1,
                            Name = "Insurance",
                            WalletId = 2
                        },
                        new
                        {
                            Id = 18,
                            Description = "Income from book sales",
                            EntryType = 0,
                            Name = "Book Sales",
                            WalletId = 2
                        },
                        new
                        {
                            Id = 19,
                            Description = "Purchase of clothing",
                            EntryType = 1,
                            Name = "Clothing",
                            WalletId = 3
                        },
                        new
                        {
                            Id = 20,
                            Description = "Bank account interest",
                            EntryType = 0,
                            Name = "Interest",
                            WalletId = 3
                        },
                        new
                        {
                            Id = 21,
                            Description = "Payment for medical services",
                            EntryType = 1,
                            Name = "Medical Bills",
                            WalletId = 4
                        },
                        new
                        {
                            Id = 22,
                            Description = "Payment for education",
                            EntryType = 1,
                            Name = "Tuition",
                            WalletId = 4
                        },
                        new
                        {
                            Id = 23,
                            Description = "Income from software sales",
                            EntryType = 0,
                            Name = "Software Sales",
                            WalletId = 5
                        },
                        new
                        {
                            Id = 24,
                            Description = "Purchase of household supplies",
                            EntryType = 1,
                            Name = "Household Supplies",
                            WalletId = 5
                        },
                        new
                        {
                            Id = 25,
                            Description = "Income from freelance writing",
                            EntryType = 0,
                            Name = "Freelance Writing",
                            WalletId = 6
                        },
                        new
                        {
                            Id = 26,
                            Description = "Donation to charity",
                            EntryType = 1,
                            Name = "Charity",
                            WalletId = 6
                        },
                        new
                        {
                            Id = 27,
                            Description = "Purchase of furniture",
                            EntryType = 1,
                            Name = "Furniture",
                            WalletId = 7
                        },
                        new
                        {
                            Id = 28,
                            Description = "Income from music sales",
                            EntryType = 0,
                            Name = "Music Sales",
                            WalletId = 7
                        },
                        new
                        {
                            Id = 29,
                            Description = "Income from tax refund",
                            EntryType = 0,
                            Name = "Tax Refund",
                            WalletId = 1
                        },
                        new
                        {
                            Id = 30,
                            Description = "Monthly subscriptions",
                            EntryType = 1,
                            Name = "Subscriptions",
                            WalletId = 2
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Balance = 1000,
                            Name = "Primary Wallet"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 1,
                            Balance = 1500,
                            Name = "Savings Wallet"
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 2,
                            Balance = 2000,
                            Name = "Investment Wallet"
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 5,
                            Balance = 2500,
                            Name = "Vacation Fund"
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 3,
                            Balance = 3000,
                            Name = "Emergency Fund"
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 4,
                            Balance = 3500,
                            Name = "Retirement Fund"
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 5,
                            Balance = 4000,
                            Name = "Education Fund"
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.FinanceOperation", b =>
                {
                    b.HasOne("Infrastructure.Models.FinanceOperationType", "Type")
                        .WithMany("FinanceOperations")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Infrastructure.Models.FinanceOperationType", b =>
                {
                    b.HasOne("Infrastructure.Models.Wallet", "Wallet")
                        .WithMany("FinanceOperationTypes")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Infrastructure.Models.Wallet", b =>
                {
                    b.HasOne("Infrastructure.Models.Account", "Account")
                        .WithMany("Wallets")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Infrastructure.Models.Account", b =>
                {
                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("Infrastructure.Models.FinanceOperationType", b =>
                {
                    b.Navigation("FinanceOperations");
                });

            modelBuilder.Entity("Infrastructure.Models.Wallet", b =>
                {
                    b.Navigation("FinanceOperationTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
